application: blank-o-matic
version: 1
runtime: python27
api_version: 1
threadsafe: yes

default_expiration: "10m"

handlers:
- url: /$
  upload: index.html
  static_files: index.html

- url: /files
  static_dir: files

- url: /components
  static_dir: components

skip_files:
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*\.md$
- ^(.*/)?.*\.log$
- ^(.*/)?app\.yaml
# ignore crufty bits in checkouts
- ^(.*/)?node_modules/.*